---
name: Build and deploy maven artifacts
on:
  push:
    tags:
      - 'release-[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import gpg key
        run: |
          echo "${{ secrets.OSS_GPG_PRIVATE_KEY }}" | base64 -d > key.file
          gpg --batch --import key.file
          rm -f key.file
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - name: Build with Maven
        run: |
          git config --global user.email "p.aichinger@googlemail.com"
          git config --global user.name "releasebot"
          echo "${{ secrets.MAVEN_SETTINGS }}" | base64 -d > settings.xml
          NEW_VERSION=$(echo $GITHUB_REF_NAME | cut -c 9-)
          echo "Preparing release version: $NEW_VERSION"
          mvn -B --settings settings.xml --no-transfer-progress release:prepare -Darguments=-Dgpg.keyname=A0CE0D27564D87E0E95E51B36698D217CB772B1C -DreleaseVersion=$NEW_VERSION
          mvn -B --settings settings.xml --no-transfer-progress release:perform -Darguments=-Dgpg.keyname=A0CE0D27564D87E0E95E51B36698D217CB772B1C
