---
name: Build and deploy maven artifacts
on:
  push:
    tags:
      - trigger-release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Import gpg key
        run: |
          echo "${{ secrets.OSS_GPG_PRIVATE_KEY }}" | base64 -d > key.file
          gpg --batch --import key.file
          rm -f key.file
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: temurin
      - name: Build with Maven
        run: |
          echo "${{ secrets.MAVEN_SETTINGS }}" | base64 -d > settings.xml
          mvn -B --setings settings.xml --no-transfer-progress release:prepare -Darguments=-Dgpg.keyname=A0CE0D27564D87E0E95E51B36698D217CB772B1C
          mvn -B --setings settings.xml --no-transfer-progress release:perform -Darguments=-Dgpg.keyname=A0CE0D27564D87E0E95E51B36698D217CB772B1C
